---
- name: Подготовка нового сервера
  hosts: all
  vars_files:
    - vars.yml 
  roles:
    - nginx
    - ssl
  handlers:
    - name: Reload Nginx
      become: yes
      service:
        name: nginx
        state: restarted
