- name: Отключение IPv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "1" # Заключение в кавычки, чтобы сохранить тип данных как строка
    state: present  # Убедитcя, что параметр существует и равен 1
  become: yes
